# Generated by Django 5.1.4 on 2025-01-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OLXAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_advertisement', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('describe', models.TextField()),
                ('date_published', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('number_of_views', models.IntegerField()),
                ('tags', models.TextField()),
                ('phone_number', models.TextField()),
            ],
        ),
    ]
