# Generated by Django 5.1.4 on 2025-01-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olxad',
            name='number_of_views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='olxad',
            name='phone_number',
            field=models.TextField(blank=True, default='-', null=True),
        ),
    ]
