# Generated by Django 5.1.4 on 2025-01-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_alter_olxad_number_of_views_alter_olxad_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='olxad',
            name='imgs_list',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
