# Generated by Django 5.1.4 on 2025-01-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_olxad_imgs_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='olxad',
            name='last_online_seller',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='olxad',
            name='name_seller',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='olxad',
            name='rating',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='olxad',
            name='region',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='olxad',
            name='register_date_seller',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
